### ISSUE TITLE
Adding playlist does not set "owner" to true

### ISSUE THREAD

**Issue by Weario** [meronbrouwer/oose-dea-eai-client#4]
When the user wants to add a new playlist, the client seems to send a body where the "owner" variable is set to false, but the readme mentions that it should send a body where the "owner" is set to true.

**Comment by meronbrouwer** [comment]
Since the server is responsible to set the Owner value, it is irrelevant what the client says. To emphasize this, the Client sets it to "false" and hopes the Server allows it to become the "owner".

**Comment by Weario** [comment]
In that case, to avoid confusion, I'd change the example JSON request body in the readme so that the owner is set to false. 
```
{
  "id"    : -1,
  "name"  : "Progressive Rock",
  "owner" : false,
  "tracks": []
},
```
It may indeed be irrelevant what the client makes of the 'owner' variable, but the current example does not match what is 'actually' being sent to the server.

I also recommend changing the text to inform the developer that the server is responsible for settng the 'owner' variable:

"Note that the client will set the id to -1, and the 'owner' variable to false. The server is responsible for generating a unique id, and setting the 'owner' variable accordingly. These must be set on the response object."

**Comment by meronbrouwer** [comment]
Issue has been resolved.
